/**
 * Projects the world once, at build time, into fixed SVG path strings.
 *
 * The Worker has a 10ms CPU budget per request, and projecting land geometry on
 * every claim would spend most of it. Runtime only has to project the handful
 * of points belonging to the route, against the identical projection recorded
 * here.
 *
 *   node --experimental-strip-types scripts/build-land.ts
 */
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { geoGraticule10, geoNaturalEarth1, geoPath } from "d3-geo";
import { feature } from "topojson-client";
import type { Topology } from "topojson-specification";

const require = createRequire(import.meta.url);
const topology = require("world-atlas/land-110m.json") as Topology;

const WIDTH = 1200;
const HEIGHT = 560;
const PAD = 10;

// Fitting to the sphere rather than to the land keeps the map centred instead
// of letting Antarctica drag everything upward.
const projection = geoNaturalEarth1().fitExtent(
  [
    [PAD, PAD],
    [WIDTH - PAD, HEIGHT - PAD],
  ],
  { type: "Sphere" },
);

const path = geoPath(projection);
const land = feature(topology, topology.objects.land);

// Whole pixels. At 1200px across, a tenth of a pixel of coastline detail costs
// bytes in every commit forever and is invisible in every one of them.
const round = (d: string) => d.replace(/\d+\.\d+/g, (n) => Number(n).toFixed(0));

const source = `// Generated by scripts/build-land.ts — do not edit.
export const WIDTH = ${WIDTH};
export const HEIGHT = ${HEIGHT};
export const SCALE = ${projection.scale()};
export const TRANSLATE: [number, number] = [${projection.translate()[0]}, ${projection.translate()[1]}];

export const SPHERE_PATH = ${JSON.stringify(round(path({ type: "Sphere" }) ?? ""))};

export const GRATICULE_PATH = ${JSON.stringify(round(path(geoGraticule10()) ?? ""))};

export const LAND_PATH = ${JSON.stringify(round(path(land) ?? ""))};
`;

writeFileSync(new URL("../src/land.ts", import.meta.url), source);

console.log(
  `src/land.ts  ${(source.length / 1024).toFixed(1)} KB  ` +
    `(${WIDTH}×${HEIGHT}, scale ${projection.scale().toFixed(2)})`,
);
